name: "Goreleaser"

on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  build-goreleaser:
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Node Build
      run: make install-ui-packages ui

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        args: release --clean --skip-validate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v3
      with:
        name: answer
        path: ./dist/*
